# Sign In
POST {{host-url}}/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "ialilat",
  "password": "2000io1w"
}
###

# Sign Up
POST {{host-url}}/auth/signup
Content-Type: application/json

{
    "firstName": "Ziouane"
  , "lastName" : "Imene"
  , "phone": "+213770474400"
  , "address" : "Algiers, Algeria"
  , "username": "iziouane"
  , "email": "ziouane.imene@gmail.com"
  , "password": "2000io1w"
}
###