# Sign In
POST {{host-url}}/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "ialilat",
  "password": "2000io1w"
}
###

# Sign Up
POST {{host-url}}/auth/signup
Content-Type: application/json

{
    "fullName": "ALILAT Imad"
  , "phone": "+213770474400"
  , "address" : "Algiers, Algeria"
  , "username": "ialilat"
  , "email": "alilat.imad@gmail.com"
  , "password": "2000io1w"
}
###