# API NOTEBOOK MANAGEMENT

GET {{host-url}}//medecin/all

###

GET {{host-url}}//medecin/appointements/1

###

# API NOTEBOOK MANAGEMENT

GET {{host-url}}//medecin/all

###
// Get
GET {{host-url}}//patient/appointements/1

###






# Sign In
POST {{host-url}}/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "ialilat",
  "password": "2000io1w"
}
###

# Sign Up
POST {{host-url}}/auth/signup
Content-Type: application/json

{
    "name": "alilat"
  , "username": "ialilat"
  , "email": "alilat.imad@gmail.com"
  , "password": "2000io1w"
//  , "roles": ["admin", "pm"]
}
###

# Get Private Event

GET {{host-url}}/private

###




# API COLORS

GET {{host-url}}/colors/all

###



# API NOTEBOOK MANAGEMENT

GET {{host-url}}//notebooks/all

###

POST {{host-url}}/notebooks
Content-Type: application/json

{
  "name": "Personal",
  "color": "#000000"
}
###

DELETE {{host-url}}/notebooks/3f6f9f6c-c3c2-40ba-a741-68615c6c8247
###



# API NOTE MANAGEMENT

GET {{host-url}}//notes/all

###

GET {{host-url}}//notes/byId/e23657d4-9df5-4d03-8023-40c44c49d362

###

POST {{host-url}}//notes
Content-Type: application/json

{
  "title": "Another Note 3",
  "text": "Another Note Description 3",
  "notebookId": "61f83802-1576-44dd-821a-e5282dc99426"
}
###

DELETE {{host-url}}//notes/5d6e01a8-ae61-4303-8385-28c0621cfaaf

###


# FEEDBACK

POST {{host-url}}//feedback
Content-Type: application/json

{
  "name": "Dan",
  "email": "dan@gmail.com",
  "feedback": "Your app is so cool"
}
###