## Remarque : il faut désactiver la sécuriter pour pouvoir tester ces EndPoints.

# private : Change Status of an appointement
POST {{host-url}}//private/events/status/52
Content-Type: application/json

{}
###

# private : delete appointment
DELETE {{host-url}}//private/events/51
###

# private : Get appointment list by day.
POST {{host-url}}//private/events/daily
Content-Type: application/json

{
  "medecinId": 1,
  "date": "2019-03-26"
}
###